# Generated by Django 3.2.2 on 2021-06-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('founded', models.TextField()),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('polygon', models.TextField()),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('line_code', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_code', models.SmallIntegerField(blank=True, null=True)),
                ('prefecture', models.CharField(max_length=10)),
                ('municipality', models.CharField(max_length=50)),
                ('district_name', models.CharField(max_length=10)),
                ('trade_price', models.BigIntegerField(blank=True, null=True)),
                ('floor_plan', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=50)),
                ('building_year', models.CharField(max_length=10)),
                ('period', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('prefecture', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'db_table': 'station',
                'managed': False,
            },
        ),
    ]
