steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/trim-tide-313616/map', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/trim-tide-313616/map']
# Collect static
# - name: "gcr.io/google-appengine/exec-wrapper"
#   args:
#     [
#       "-i",
#       "gcr.io/trim-tide-313616/map",
#       "-s",
#       "trim-tide-313616:asia-northeast1:map",
#       "-e",
#       "SETTINGS_NAME=django_settings",
#       "--",
#       "python",
#       "manage.py",
#       "collectstatic",
#       "--verbosity",
#       "2",
#       "--no-input"
#     ]
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'map', '--image', 'gcr.io/trim-tide-313616/map', '--region', 'asia-northeast1', '--platform', 'managed']
images:
- gcr.io/trim-tide-313616/map