steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/trim-tide-313616/map', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/trim-tide-313616/map']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'map', '--image', 'gcr.io/trim-tide-313616/map', '--region', 'asia-northeast1', '--platform', 'managed']
images:
- gcr.io/trim-tide-313616/map